[package]
name = "megalinref"
version = "0.1.0"
edition="2021"

[lib]
name = "megalinref"
crate-type = ["cdylib"]

[package.metadata.maturin]
python-source = "python"

[dependencies]
geo-types = {version = "0.7" ,  features=["use-rstar", "rstar"]}
geo       = {version = "0.18",  features = ["use-serde"]}
pyo3      = {version = "0.15",  features = ["extension-module"]}
serde     = {version = "1.0"}
bincode   = {version = "1.3"}
rayon     = {version = "1.5"}