[package]
name = "megalinref"
version = "0.1.0"
edition="2021"

[lib]
name = "megalinref"
crate-type = ["cdylib"]

[package.metadata.maturin]
python-source = "python"

[dependencies.pyo3]
version = "0.15"
features = ["extension-module"]

[dependencies.geo]
version = "0.18"
features = ["use-serde"]

[dependencies]
serde="1.0"
bincode="1.3"
rstar = "0.9"