[package]
name = "megalinref"
version = "0.1.0"
edition="2018"

[lib]
name = "megalinref"
crate-type = ["cdylib"]

[package.metadata.maturin]
python-source = "python"

[dependencies.pyo3]
version = "0.15"
features = ["extension-module"]

[dependencies.geo]
version = "0.18.0"
features = ["use-serde"]

[dependencies.serde]
version="1.0"

[dependencies]
